package: mform
version: '8.0.0-beta4'
name: MForm
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/mform
page:
    title: 'translate:title'
    pjax: true
    perm: admin[]
    icon: rex-icon fa-subway
    subpages:
        demo:
            title: 'translate:reference_demo'
            subpages:
                demo_base: { title: 'translate:demo_base' }
                demo_wrapper: { title: 'translate:demo_wrapper' }
                demo_extended: { title: 'translate:demo_extended' }
                demo_repeater: { title: 'translate:demo_repeater' }
                demo_expert: { title: 'translate:demo_expert' }
        changelog:
            title: 'translate:changelog'
            subPath: CHANGELOG.md
            itemClass: pull-right
        help:
            title: 'translate:help'
            subPath: README.md
            itemClass: pull-right

requires:
    php: '>=7.6'
    redaxo: '^5.10.0'

conflicts:
    packages:
        ui_tools: '<1.0.0'
        yform: '<4.2.1'
