package: mform
version: '8.0.0-beta4'
name: MForm
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/mform
page:
    title: 'translate:title'
    pjax: true
    perm: admin[]
    icon: rex-icon fa-solid fa-diagram-next
    subpages:
        demo:
            title: 'translate:demo'
            icon: rex-icon fa-desktop
            perm: mform[demo]

requires:
    php: '>=7.6'
    redaxo: '^5.17.0'

conflicts:
    packages:
        ui_tools: '<1.0.0'
